title: "R 팁 저장소"
description: "R로 데이터 분석과 시각화 팁을 체계적으로 정리하고 공유하는 공간입니다"
baseurl: "" # Root URL ("" for GitHub Pages root)
url: "https://codebyday.github.io/ggsave"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

# Build settings
markdown: kramdown
kramdown:
  input: GFM